#!/bin/bash

# use: s5 JSFILE OPTIONS_TO_MAIN
# e.g. s5 test.js -eval
# e.g. s5 stdin -eval

BASE_PATH=`dirname $0`/..

TMP=`mktemp -t js.XXXXXX`
if [ $1 == "stdin" ]; then
  cat>$TMP
  JSFILE=$TMP
else
  JSFILE=$1
fi

ocamlrun $BASE_PATH/obj/s5.d.byte \
  -desugar $JSFILE \
  -env $BASE_PATH/envs/regexp.env -apply \
  -desugar $BASE_PATH/lib/js-regexp/regexp.js -to-env -apply \
  -env $BASE_PATH/envs/json.env -apply \
  -desugar $BASE_PATH/lib/json/json_parse.js -to-env -apply \
  -desugar $BASE_PATH/lib/json/json2.js -to-env -apply \
  -internal-env env-vars -apply \
  -env $BASE_PATH/envs/es5.env -apply \
  ${@:2}

EX=$?
rm $TMP

exit $EX
