#!/bin/bash

BASE_PATH=`dirname $0`/..

TMP=`mktemp -t js.XXXXXX`
if [ $# -eq 0 ]; then
  cat>$TMP
else
  TMP=$1
fi

RETMP=`mktemp -t js.XXXXXX`
$BASE_PATH/bin/js $BASE_PATH/tests/json_print.js $BASE_PATH/lib/js-regexp/regexp.js > $RETMP

$BASE_PATH/bin/js $BASE_PATH/tests/json_print.js $TMP > $TMP.ast
ocamlrun $BASE_PATH/obj/s5.d.byte -set-json $BASE_PATH/tests/desugar.sh \
  -js $TMP.ast -js-to-s5 \
  -print-src
rm $RETMP
rm $TMP.ast
